name: Code Formatting Check

on:
  pull_request:
    paths:
      - ".github/workflows/code-formatting-check.yml"
      - "examples_formatter.sh"
      - "examples/**"
  push:
    paths:
      - ".github/workflows/code-formatting-check.yml"
      - "examples_formatter.sh"
      - "examples/**"

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    env:
      # See: https://sourceforge.net/projects/astyle/files/astyle/
      ASTYLE_VERSION: 3.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # See: http://astyle.sourceforge.net/
      - name: Download Artistic Style
        uses: carlosperate/download-file-action@v1
        with:
          file-url: https://iweb.dl.sourceforge.net/project/astyle/astyle/astyle%20${{ env.ASTYLE_VERSION }}/astyle_${{ env.ASTYLE_VERSION }}_linux.tar.gz
          location: ${{ runner.temp }}/astyle

      # See: http://astyle.sourceforge.net/install.html#_GCC_Makefile
      - name: Build Artistic Style
        run: |
          # Build Artistic Style
          cd "${{ runner.temp }}/astyle"
          tar --extract --file="astyle_${{ env.ASTYLE_VERSION }}_linux.tar.gz"
          cd "astyle/build/gcc"
          make
          # Add installation to PATH:
          # See: https://docs.github.com/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
          echo "${{ runner.temp }}/astyle/astyle/build/gcc/bin" >> "$GITHUB_PATH"

      - name: Format examples
        run: ./examples_formatter.sh

      - name: Check formatting
        run: |
          if ! git diff --color --exit-code; then
            echo "Please do an Auto Format on the sketches:"
            echo "Arduino IDE: Tools > Auto Format"
            echo "Arduino Web Editor: Ctrl + B"
            exit 1
          fi
